export interface KanbanColumn { id: string; title: string; }
export interface KanbanCard { columnId: string; id: string; metadata: Record<string, string>; title: string; }
export interface KanbanDiagramSnapshot { cards: KanbanCard[]; columns: KanbanColumn[]; }

interface Line { end: number; raw: string; start: number; text: string; }
interface ColumnRecord extends KanbanColumn { line: Line; }
interface CardRecord extends KanbanCard { line: Line; }
interface Parsed { cards: CardRecord[]; columns: ColumnRecord[]; }

const HEADER = /^\s*kanban\s*$/i;
const ID = '[A-Za-z_][A-Za-z0-9_-]*';
const COLUMN = new RegExp(`^(\\s*)(${ID})\\[([^\\[\\]\\r\\n]+)\\]\\s*$`);
const CARD = new RegExp(`^(\\s+)(${ID})\\[([^\\[\\]\\r\\n]+)\\](?:@\\{\\s*(.*?)\\s*\\})?\\s*$`);
const META = /([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(?:"([^"\r\n{}]+)"|([A-Za-z_][A-Za-z0-9_.-]*))/g;

export function isKanbanDiagramSource(source: string): boolean { return parseKanban(source) !== null; }
export function isKanbanSourceRepresentable(source: string): boolean { return parseKanban(source) !== null; }
export function getKanbanDiagramSnapshot(source: string): KanbanDiagramSnapshot { const parsed = requireKanban(source); return { columns: parsed.columns.map(({ id, title }) => ({ id, title })), cards: parsed.cards.map(({ columnId, id, metadata, title }) => ({ columnId, id, title, metadata: { ...metadata } })) }; }

export function addKanbanColumn(source: string, column: KanbanColumn): string {
  const value = normalizeColumn(column); if (!source.trim()) return `kanban\n  ${formatColumn(value)}`; const parsed = requireKanban(source); const id = uniqueId(value.id, allIds(parsed)); return appendAndValidate(source, `  ${formatColumn({ ...value, id })}`);
}
export function editKanbanColumn(source: string, id: string, patch: Partial<KanbanColumn> & { id?: string }): string {
  const parsed = requireKanban(source); const current = findColumn(parsed, id); const value = normalizeColumn({ ...current, ...patch, id: patch.id ?? current.id }); const occupied = allIds(parsed); occupied.delete(current.id); if (value.id !== current.id && occupied.has(value.id)) throw new Error(`A Kanban item named ${value.id} already exists.`);
  let next = replaceLine(source, current.line, `${indent(current.line)}${formatColumn(value)}`); if (value.id !== current.id) next = replaceCardColumn(next, current.id, value.id); return requireKanban(next), next;
}
export function deleteKanbanColumn(source: string, id: string): string {
  const parsed = requireKanban(source); const column = findColumn(parsed, id); const records = [column.line, ...parsed.cards.filter((card) => card.columnId === id).map((card) => card.line)]; return deleteLines(source, records);
}
export function addKanbanCard(source: string, card: KanbanCard): string {
  const parsed = requireKanban(source); const value = normalizeCard(card); const column = findColumn(parsed, value.columnId); const id = uniqueId(value.id, allIds(parsed)); const insertion = `${indent(column.line)}  ${formatCard({ ...value, id })}${lineEnding(source)}`; const nextColumn = nextColumnRecord(parsed, column); const position = nextColumn?.line.start ?? source.length; const prefix = source.slice(0, position); const separator = prefix && !/(?:\r\n|\n|\r)$/.test(prefix) ? lineEnding(source) : ''; const next = `${prefix}${separator}${insertion}${source.slice(position)}`; return requireKanban(next), next;
}
export function editKanbanCard(source: string, id: string, patch: Partial<Omit<KanbanCard, 'columnId'>> & { id?: string }): string {
  const parsed = requireKanban(source); const current = findCard(parsed, id); const value = normalizeCard({ ...current, ...patch, id: patch.id ?? current.id, metadata: patch.metadata ?? current.metadata }); const occupied = allIds(parsed); occupied.delete(current.id); if (value.id !== current.id && occupied.has(value.id)) throw new Error(`A Kanban item named ${value.id} already exists.`); return replaceAndValidate(source, current.line, `${indent(current.line)}${formatCard(value)}`);
}
export function deleteKanbanCard(source: string, id: string): string { const parsed = requireKanban(source); const card = findCard(parsed, id); return deleteLines(source, [card.line]); }
/** Moves a card to a column/index while keeping the document's line endings at their physical positions. */
export function moveKanbanCard(source: string, id: string, columnId: string, targetIndex: number): string {
  const parsed = requireKanban(source); const current = findCard(parsed, id); const target = findColumn(parsed, columnId); const cards = parsed.cards.filter((card) => card.columnId === target.id && card.id !== current.id); if (!Number.isInteger(targetIndex) || targetIndex < 0 || targetIndex > cards.length) throw new Error('Kanban card position is out of range.');
  const before = cards[targetIndex]; const nextColumn = nextColumnRecord(parsed, target); const next = moveLineText(source, current.line, `${indent(target.line)}  ${formatCard({ ...current, columnId: target.id })}`, before?.line ?? nextColumn?.line);
  return requireKanban(next), next;
}
export function setKanbanCardMetadata(source: string, id: string, metadata: Record<string, string>): string { return editKanbanCard(source, id, { metadata }); }

function parseKanban(source: string): Parsed | null {
  const lines = splitLines(source); const headerIndex = firstStatement(lines); if (!HEADER.test(lines[headerIndex]?.text.replace(/^\uFEFF/, '') ?? '')) return null; const columns: ColumnRecord[] = []; const cards: CardRecord[] = []; let current: ColumnRecord | undefined;
  for (let index = headerIndex + 1; index < lines.length; index += 1) { const line = lines[index]!; if (!line.text.trim() || ignorable(line.text)) continue; const card = line.text.match(CARD); const column = line.text.match(COLUMN); const depth = indent(line).length; if (current && card && depth > indent(current.line).length) { const metadata = parseMetadata(card[4] ?? ''); if (!metadata) return null; cards.push({ line, columnId: current.id, id: card[2]!, title: card[3]!.trim(), metadata }); continue; } if (column) { current = { line, id: column[2]!, title: column[3]!.trim() }; columns.push(current); continue; } return null; }
  const parsed = { columns, cards }; try { validate(parsed); return parsed; } catch { return null; }
}
function parseMetadata(input: string): Record<string, string> | null { if (!input) return {}; const metadata: Record<string, string> = {}; META.lastIndex = 0; let consumed = ''; let match: RegExpExecArray | null; while ((match = META.exec(input))) { consumed += match[0]!; const key = match[1]!; if (metadata[key] !== undefined) return null; metadata[key] = (match[2] ?? match[3]!).trim(); const comma = input.slice(META.lastIndex).match(/^\s*,\s*/); if (comma) { consumed += comma[0]; META.lastIndex += comma[0].length; } } return consumed === input ? metadata : null; }
function validate(parsed: Parsed): void { const ids = new Set<string>(); for (const item of [...parsed.columns, ...parsed.cards]) { if (ids.has(item.id)) throw new Error('Kanban column and card identifiers must be unique.'); ids.add(item.id); } if (!parsed.columns.length && parsed.cards.length) throw new Error('Kanban cards need a column.'); }
function requireKanban(source: string): Parsed { const parsed = parseKanban(source); if (!parsed) throw new Error('This source is not a safely representable Kanban diagram.'); return parsed; }
function findColumn(parsed: Parsed, id: string): ColumnRecord { const column = parsed.columns.find((item) => item.id === id); if (!column) throw new Error(`Kanban column ${id} no longer exists.`); return column; } function findCard(parsed: Parsed, id: string): CardRecord { const card = parsed.cards.find((item) => item.id === id); if (!card) throw new Error(`Kanban card ${id} no longer exists.`); return card; } function nextColumnRecord(parsed: Parsed, column: ColumnRecord): ColumnRecord | undefined { return parsed.columns[parsed.columns.indexOf(column) + 1]; }
function normalizeColumn(value: KanbanColumn): KanbanColumn { return { id: normalizeId(value.id), title: text(value.title, 'Kanban column titles') }; } function normalizeCard(value: KanbanCard): KanbanCard { return { id: normalizeId(value.id), columnId: normalizeId(value.columnId), title: text(value.title, 'Kanban card titles'), metadata: normalizeMetadata(value.metadata) }; } function normalizeMetadata(metadata: Record<string, string>): Record<string, string> { return Object.fromEntries(Object.entries(metadata).map(([key, value]) => { if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(key)) throw new Error('Kanban metadata keys must be identifiers.'); return [key, text(value, `Kanban metadata ${key}`)]; })); }
function formatColumn(value: KanbanColumn): string { return `${value.id}[${value.title}]`; } function formatCard(value: KanbanCard): string { const entries = Object.entries(value.metadata); return `${value.id}[${value.title}]${entries.length ? `@{ ${entries.map(([key, item]) => `${key}: "${item}"`).join(', ')} }` : ''}`; } function uniqueId(base: string, ids: ReadonlySet<string>): string { let candidate = base; let suffix = 2; while (ids.has(candidate)) { candidate = `${base}${suffix}`; suffix += 1; } return candidate; } function allIds(parsed: Parsed): Set<string> { return new Set([...parsed.columns, ...parsed.cards].map((item) => item.id)); }
function replaceCardColumn(source: string, from: string, to: string): string { const parsed = requireKanban(source); const cards = parsed.cards.filter((card) => card.columnId === from); if (!cards.length) return source; const without = deleteLines(source, cards.map((card) => card.line)); const after = requireKanban(without); const target = findColumn(after, to); const value = cards.map((card) => `${indent(target.line)}  ${formatCard({ ...card, columnId: to })}${lineEnding(without)}`).join(''); const nextColumn = nextColumnRecord(after, target); const position = nextColumn?.line.start ?? without.length; return `${without.slice(0, position)}${value}${without.slice(position)}`; }
function normalizeId(value: string): string { const id = value.trim(); if (!new RegExp(`^${ID}$`).test(id)) throw new Error('Kanban identifiers must be Mermaid-safe identifiers.'); return id; } function text(value: string, noun: string): string { const text = value.trim(); if (!text || /[\[\]{}"\r\n]/.test(text)) throw new Error(`${noun} must be one-line Mermaid labels.`); return text; }
function splitLines(source: string): Line[] { const lines: Line[] = []; const matcher = /.*?(?:\r\n|\n|\r|$)/g; let match: RegExpExecArray | null; while ((match = matcher.exec(source)) && match[0]) { const raw = match[0]; lines.push({ start: match.index, end: match.index + raw.length, raw, text: raw.replace(/\r\n|\n|\r$/, '') }); } return lines; } function firstStatement(lines: readonly Line[]): number { let index = 0; if (lines[0]?.text.replace(/^\uFEFF/, '').trim() === '---') { const close = lines.findIndex((line, candidate) => candidate > 0 && line.text.trim() === '---'); index = close < 0 ? lines.length : close + 1; } while (index < lines.length && (!lines[index]!.text.trim() || ignorable(lines[index]!.text))) index += 1; return index; } function ignorable(text: string): boolean { return /^\s*%%/.test(text); } function indent(line: Line): string { return line.text.match(/^\s*/)?.[0] ?? ''; } function lineEnding(source: string): string { return source.includes('\r\n') ? '\r\n' : source.includes('\r') ? '\r' : '\n'; }
function append(source: string, statement: string): string { const ending = lineEnding(source); return `${source}${source && !/(?:\r\n|\n|\r)$/.test(source) ? ending : ''}${statement}`; } function appendAndValidate(source: string, statement: string): string { const next = append(source, statement); return requireKanban(next), next; } function replaceLine(source: string, line: Line, value: string): string { return `${source.slice(0, line.start)}${value}${line.raw.slice(line.text.length)}${source.slice(line.end)}`; } function replaceAndValidate(source: string, line: Line, value: string): string { const next = replaceLine(source, line, value); return requireKanban(next), next; } function deleteLines(source: string, lines: readonly Line[]): string { return [...lines].sort((left, right) => right.start - left.start).reduce((next, line) => `${next.slice(0, line.start)}${next.slice(line.end)}`, source); }
function moveLineText(source: string, line: Line, text: string, before?: Line): string { const lines = splitLines(source); const endings = lines.map((item) => item.raw.slice(item.text.length)); const sourceIndex = lines.findIndex((item) => item.start === line.start); if (sourceIndex < 0) throw new Error('Kanban card no longer exists.'); const [moved] = lines.splice(sourceIndex, 1); if (!moved) throw new Error('Kanban card no longer exists.'); const destination = before ? lines.findIndex((item) => item.start === before.start) : lines.length; const insertion = destination < 0 ? lines.length : destination; lines.splice(insertion, 0, { ...moved, text }); return lines.map((item, index) => `${item.text}${endings[index] ?? ''}`).join(''); }
